import type { Metadata } from "next";
import { Fjord_One } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";



const fjord = Fjord_One({
  weight: "400",
  subsets: ["latin"],
  style: "normal",
})
export const metadata: Metadata = {
  title: "Manishh-Full Stack Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fjord.className} antialiased `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        <Toaster />
        </ThemeProvider>
        
      </body>
    </html>
  );
}
